// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema WorkflowEventBinding
 */
export class WorkflowEventBinding extends ApiObject {
  /**
   * Returns the apiVersion and kind for "WorkflowEventBinding"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'argoproj.io/v1alpha1',
    kind: 'WorkflowEventBinding',
  }

  /**
   * Renders a Kubernetes manifest for "WorkflowEventBinding".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: WorkflowEventBindingProps): any {
    return {
      ...WorkflowEventBinding.GVK,
      ...toJson_WorkflowEventBindingProps(props),
    };
  }

  /**
   * Defines a "WorkflowEventBinding" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: WorkflowEventBindingProps) {
    super(scope, id, {
      ...WorkflowEventBinding.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...WorkflowEventBinding.GVK,
      ...toJson_WorkflowEventBindingProps(resolved),
    };
  }
}

/**
 * @schema WorkflowEventBinding
 */
export interface WorkflowEventBindingProps {
  /**
   * @schema WorkflowEventBinding#metadata
   */
  readonly metadata: ApiObjectMetadata;

  /**
   * @schema WorkflowEventBinding#spec
   */
  readonly spec: WorkflowEventBindingSpec;

}

/**
 * Converts an object of type 'WorkflowEventBindingProps' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingProps(obj: WorkflowEventBindingProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_WorkflowEventBindingSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpec
 */
export interface WorkflowEventBindingSpec {
  /**
   * @schema WorkflowEventBindingSpec#event
   */
  readonly event: WorkflowEventBindingSpecEvent;

  /**
   * @schema WorkflowEventBindingSpec#submit
   */
  readonly submit?: WorkflowEventBindingSpecSubmit;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpec' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpec(obj: WorkflowEventBindingSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'event': toJson_WorkflowEventBindingSpecEvent(obj.event),
    'submit': toJson_WorkflowEventBindingSpecSubmit(obj.submit),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecEvent
 */
export interface WorkflowEventBindingSpecEvent {
  /**
   * @schema WorkflowEventBindingSpecEvent#selector
   */
  readonly selector: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecEvent' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecEvent(obj: WorkflowEventBindingSpecEvent | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'selector': obj.selector,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmit
 */
export interface WorkflowEventBindingSpecSubmit {
  /**
   * @schema WorkflowEventBindingSpecSubmit#arguments
   */
  readonly arguments?: WorkflowEventBindingSpecSubmitArguments;

  /**
   * @schema WorkflowEventBindingSpecSubmit#metadata
   */
  readonly metadata?: any;

  /**
   * @schema WorkflowEventBindingSpecSubmit#workflowTemplateRef
   */
  readonly workflowTemplateRef: WorkflowEventBindingSpecSubmitWorkflowTemplateRef;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmit' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmit(obj: WorkflowEventBindingSpecSubmit | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'arguments': toJson_WorkflowEventBindingSpecSubmitArguments(obj.arguments),
    'metadata': obj.metadata,
    'workflowTemplateRef': toJson_WorkflowEventBindingSpecSubmitWorkflowTemplateRef(obj.workflowTemplateRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArguments
 */
export interface WorkflowEventBindingSpecSubmitArguments {
  /**
   * @schema WorkflowEventBindingSpecSubmitArguments#artifacts
   */
  readonly artifacts?: WorkflowEventBindingSpecSubmitArgumentsArtifacts[];

  /**
   * @schema WorkflowEventBindingSpecSubmitArguments#parameters
   */
  readonly parameters?: WorkflowEventBindingSpecSubmitArgumentsParameters[];

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArguments' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArguments(obj: WorkflowEventBindingSpecSubmitArguments | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'artifacts': obj.artifacts?.map(y => toJson_WorkflowEventBindingSpecSubmitArgumentsArtifacts(y)),
    'parameters': obj.parameters?.map(y => toJson_WorkflowEventBindingSpecSubmitArgumentsParameters(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitWorkflowTemplateRef
 */
export interface WorkflowEventBindingSpecSubmitWorkflowTemplateRef {
  /**
   * @schema WorkflowEventBindingSpecSubmitWorkflowTemplateRef#clusterScope
   */
  readonly clusterScope?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitWorkflowTemplateRef#name
   */
  readonly name?: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitWorkflowTemplateRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitWorkflowTemplateRef(obj: WorkflowEventBindingSpecSubmitWorkflowTemplateRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'clusterScope': obj.clusterScope,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifacts {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#archive
   */
  readonly archive?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#archiveLogs
   */
  readonly archiveLogs?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#artifactGC
   */
  readonly artifactGc?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#artifactory
   */
  readonly artifactory?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#azure
   */
  readonly azure?: WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#deleted
   */
  readonly deleted?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#from
   */
  readonly from?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#fromExpression
   */
  readonly fromExpression?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#gcs
   */
  readonly gcs?: WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#git
   */
  readonly git?: WorkflowEventBindingSpecSubmitArgumentsArtifactsGit;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#globalName
   */
  readonly globalName?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#hdfs
   */
  readonly hdfs?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#http
   */
  readonly http?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#mode
   */
  readonly mode?: number;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#name
   */
  readonly name: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#optional
   */
  readonly optional?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#oss
   */
  readonly oss?: WorkflowEventBindingSpecSubmitArgumentsArtifactsOss;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#path
   */
  readonly path?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#raw
   */
  readonly raw?: WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#recurseMode
   */
  readonly recurseMode?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#s3
   */
  readonly s3?: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifacts#subPath
   */
  readonly subPath?: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifacts' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifacts(obj: WorkflowEventBindingSpecSubmitArgumentsArtifacts | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'archive': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive(obj.archive),
    'archiveLogs': obj.archiveLogs,
    'artifactGC': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc(obj.artifactGc),
    'artifactory': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory(obj.artifactory),
    'azure': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure(obj.azure),
    'deleted': obj.deleted,
    'from': obj.from,
    'fromExpression': obj.fromExpression,
    'gcs': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs(obj.gcs),
    'git': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGit(obj.git),
    'globalName': obj.globalName,
    'hdfs': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs(obj.hdfs),
    'http': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp(obj.http),
    'mode': obj.mode,
    'name': obj.name,
    'optional': obj.optional,
    'oss': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOss(obj.oss),
    'path': obj.path,
    'raw': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw(obj.raw),
    'recurseMode': obj.recurseMode,
    's3': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3(obj.s3),
    'subPath': obj.subPath,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsParameters
 */
export interface WorkflowEventBindingSpecSubmitArgumentsParameters {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParameters#default
   */
  readonly default?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParameters#description
   */
  readonly description?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParameters#enum
   */
  readonly enum?: string[];

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParameters#globalName
   */
  readonly globalName?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParameters#name
   */
  readonly name: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParameters#value
   */
  readonly value?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParameters#valueFrom
   */
  readonly valueFrom?: WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsParameters' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsParameters(obj: WorkflowEventBindingSpecSubmitArgumentsParameters | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'default': obj.default,
    'description': obj.description,
    'enum': obj.enum?.map(y => y),
    'globalName': obj.globalName,
    'name': obj.name,
    'value': obj.value,
    'valueFrom': toJson_WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom(obj.valueFrom),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive#none
   */
  readonly none?: any;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive#tar
   */
  readonly tar?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive#zip
   */
  readonly zip?: any;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsArchive | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'none': obj.none,
    'tar': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar(obj.tar),
    'zip': obj.zip,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc#podMetadata
   */
  readonly podMetadata?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc#serviceAccountName
   */
  readonly serviceAccountName?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc#strategy
   */
  readonly strategy?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcStrategy;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGc | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'podMetadata': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata(obj.podMetadata),
    'serviceAccountName': obj.serviceAccountName,
    'strategy': obj.strategy,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory#passwordSecret
   */
  readonly passwordSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory#url
   */
  readonly url: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory#usernameSecret
   */
  readonly usernameSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactory | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'passwordSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret(obj.passwordSecret),
    'url': obj.url,
    'usernameSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret(obj.usernameSecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure#accountKeySecret
   */
  readonly accountKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure#blob
   */
  readonly blob: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure#container
   */
  readonly container: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure#endpoint
   */
  readonly endpoint: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure#useSDKCreds
   */
  readonly useSdkCreds?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsAzure | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accountKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret(obj.accountKeySecret),
    'blob': obj.blob,
    'container': obj.container,
    'endpoint': obj.endpoint,
    'useSDKCreds': obj.useSdkCreds,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs#bucket
   */
  readonly bucket?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs#serviceAccountKeySecret
   */
  readonly serviceAccountKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsGcs | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'bucket': obj.bucket,
    'key': obj.key,
    'serviceAccountKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret(obj.serviceAccountKeySecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsGit {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#branch
   */
  readonly branch?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#depth
   */
  readonly depth?: number;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#disableSubmodules
   */
  readonly disableSubmodules?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#fetch
   */
  readonly fetch?: string[];

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#insecureIgnoreHostKey
   */
  readonly insecureIgnoreHostKey?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#passwordSecret
   */
  readonly passwordSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#repo
   */
  readonly repo: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#revision
   */
  readonly revision?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#singleBranch
   */
  readonly singleBranch?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#sshPrivateKeySecret
   */
  readonly sshPrivateKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGit#usernameSecret
   */
  readonly usernameSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsGit' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGit(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsGit | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'branch': obj.branch,
    'depth': obj.depth,
    'disableSubmodules': obj.disableSubmodules,
    'fetch': obj.fetch?.map(y => y),
    'insecureIgnoreHostKey': obj.insecureIgnoreHostKey,
    'passwordSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret(obj.passwordSecret),
    'repo': obj.repo,
    'revision': obj.revision,
    'singleBranch': obj.singleBranch,
    'sshPrivateKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret(obj.sshPrivateKeySecret),
    'usernameSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret(obj.usernameSecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#addresses
   */
  readonly addresses?: string[];

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#force
   */
  readonly force?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#hdfsUser
   */
  readonly hdfsUser?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#krbCCacheSecret
   */
  readonly krbCCacheSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#krbConfigConfigMap
   */
  readonly krbConfigConfigMap?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#krbKeytabSecret
   */
  readonly krbKeytabSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#krbRealm
   */
  readonly krbRealm?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#krbServicePrincipalName
   */
  readonly krbServicePrincipalName?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#krbUsername
   */
  readonly krbUsername?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs#path
   */
  readonly path: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfs | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'addresses': obj.addresses?.map(y => y),
    'force': obj.force,
    'hdfsUser': obj.hdfsUser,
    'krbCCacheSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret(obj.krbCCacheSecret),
    'krbConfigConfigMap': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap(obj.krbConfigConfigMap),
    'krbKeytabSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret(obj.krbKeytabSecret),
    'krbRealm': obj.krbRealm,
    'krbServicePrincipalName': obj.krbServicePrincipalName,
    'krbUsername': obj.krbUsername,
    'path': obj.path,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp#auth
   */
  readonly auth?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp#headers
   */
  readonly headers?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders[];

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp#url
   */
  readonly url: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttp | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'auth': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth(obj.auth),
    'headers': obj.headers?.map(y => toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders(y)),
    'url': obj.url,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsOss {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#accessKeySecret
   */
  readonly accessKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#bucket
   */
  readonly bucket?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#createBucketIfNotPresent
   */
  readonly createBucketIfNotPresent?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#endpoint
   */
  readonly endpoint?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#lifecycleRule
   */
  readonly lifecycleRule?: WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#secretKeySecret
   */
  readonly secretKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#securityToken
   */
  readonly securityToken?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOss#useSDKCreds
   */
  readonly useSdkCreds?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsOss' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOss(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsOss | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accessKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret(obj.accessKeySecret),
    'bucket': obj.bucket,
    'createBucketIfNotPresent': obj.createBucketIfNotPresent,
    'endpoint': obj.endpoint,
    'key': obj.key,
    'lifecycleRule': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule(obj.lifecycleRule),
    'secretKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret(obj.secretKeySecret),
    'securityToken': obj.securityToken,
    'useSDKCreds': obj.useSdkCreds,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw#data
   */
  readonly data: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsRaw | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'data': obj.data,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsS3 {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#accessKeySecret
   */
  readonly accessKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#bucket
   */
  readonly bucket?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#caSecret
   */
  readonly caSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#createBucketIfNotPresent
   */
  readonly createBucketIfNotPresent?: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#encryptionOptions
   */
  readonly encryptionOptions?: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#endpoint
   */
  readonly endpoint?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#insecure
   */
  readonly insecure?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#key
   */
  readonly key?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#region
   */
  readonly region?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#roleARN
   */
  readonly roleArn?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#secretKeySecret
   */
  readonly secretKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3#useSDKCreds
   */
  readonly useSdkCreds?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsS3' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3 | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'accessKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret(obj.accessKeySecret),
    'bucket': obj.bucket,
    'caSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret(obj.caSecret),
    'createBucketIfNotPresent': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent(obj.createBucketIfNotPresent),
    'encryptionOptions': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions(obj.encryptionOptions),
    'endpoint': obj.endpoint,
    'insecure': obj.insecure,
    'key': obj.key,
    'region': obj.region,
    'roleARN': obj.roleArn,
    'secretKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret(obj.secretKeySecret),
    'useSDKCreds': obj.useSdkCreds,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom
 */
export interface WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#configMapKeyRef
   */
  readonly configMapKeyRef?: WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#default
   */
  readonly default?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#event
   */
  readonly event?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#expression
   */
  readonly expression?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#jqFilter
   */
  readonly jqFilter?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#jsonPath
   */
  readonly jsonPath?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#parameter
   */
  readonly parameter?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#path
   */
  readonly path?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom#supplied
   */
  readonly supplied?: any;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom(obj: WorkflowEventBindingSpecSubmitArgumentsParametersValueFrom | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'configMapKeyRef': toJson_WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef(obj.configMapKeyRef),
    'default': obj.default,
    'event': obj.event,
    'expression': obj.expression,
    'jqFilter': obj.jqFilter,
    'jsonPath': obj.jsonPath,
    'parameter': obj.parameter,
    'path': obj.path,
    'supplied': obj.supplied,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar#compressionLevel
   */
  readonly compressionLevel?: number;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsArchiveTar | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'compressionLevel': obj.compressionLevel,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata#annotations
   */
  readonly annotations?: { [key: string]: string };

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata#labels
   */
  readonly labels?: { [key: string]: string };

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcPodMetadata | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'annotations': ((obj.annotations) === undefined) ? undefined : (Object.entries(obj.annotations).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'labels': ((obj.labels) === undefined) ? undefined : (Object.entries(obj.labels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcStrategy
 */
export enum WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactGcStrategy {
  /** OnWorkflowCompletion */
  ON_WORKFLOW_COMPLETION = "OnWorkflowCompletion",
  /** OnWorkflowDeletion */
  ON_WORKFLOW_DELETION = "OnWorkflowDeletion",
  /** Never */
  NEVER = "Never",
}

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryPasswordSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsArtifactoryUsernameSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsAzureAccountKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsGcsServiceAccountKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsGitPasswordSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsGitSshPrivateKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsGitUsernameSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbCCacheSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbConfigConfigMap | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHdfsKrbKeytabSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth#basicAuth
   */
  readonly basicAuth?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth#clientCert
   */
  readonly clientCert?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth#oauth2
   */
  readonly oauth2?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuth | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'basicAuth': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth(obj.basicAuth),
    'clientCert': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert(obj.clientCert),
    'oauth2': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2(obj.oauth2),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders#name
   */
  readonly name: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders#value
   */
  readonly value: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpHeaders | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'value': obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsOssAccessKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule#markDeletionAfterDays
   */
  readonly markDeletionAfterDays?: number;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule#markInfrequentAccessAfterDays
   */
  readonly markInfrequentAccessAfterDays?: number;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsOssLifecycleRule | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'markDeletionAfterDays': obj.markDeletionAfterDays,
    'markInfrequentAccessAfterDays': obj.markInfrequentAccessAfterDays,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsOssSecretKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3AccessKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CaSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent#objectLocking
   */
  readonly objectLocking?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3CreateBucketIfNotPresent | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'objectLocking': obj.objectLocking,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions#enableEncryption
   */
  readonly enableEncryption?: boolean;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions#kmsEncryptionContext
   */
  readonly kmsEncryptionContext?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions#kmsKeyId
   */
  readonly kmsKeyId?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions#serverSideCustomerKeySecret
   */
  readonly serverSideCustomerKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptions | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'enableEncryption': obj.enableEncryption,
    'kmsEncryptionContext': obj.kmsEncryptionContext,
    'kmsKeyId': obj.kmsKeyId,
    'serverSideCustomerKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret(obj.serverSideCustomerKeySecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3SecretKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef
 */
export interface WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef(obj: WorkflowEventBindingSpecSubmitArgumentsParametersValueFromConfigMapKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth#passwordSecret
   */
  readonly passwordSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth#usernameSecret
   */
  readonly usernameSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuth | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'passwordSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret(obj.passwordSecret),
    'usernameSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret(obj.usernameSecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert#clientCertSecret
   */
  readonly clientCertSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert#clientKeySecret
   */
  readonly clientKeySecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCert | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'clientCertSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret(obj.clientCertSecret),
    'clientKeySecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret(obj.clientKeySecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2 {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2#clientIDSecret
   */
  readonly clientIdSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2#clientSecretSecret
   */
  readonly clientSecretSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2#endpointParams
   */
  readonly endpointParams?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams[];

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2#scopes
   */
  readonly scopes?: string[];

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2#tokenURLSecret
   */
  readonly tokenUrlSecret?: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2 | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'clientIDSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret(obj.clientIdSecret),
    'clientSecretSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret(obj.clientSecretSecret),
    'endpointParams': obj.endpointParams?.map(y => toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams(y)),
    'scopes': obj.scopes?.map(y => y),
    'tokenURLSecret': toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret(obj.tokenUrlSecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsS3EncryptionOptionsServerSideCustomerKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthPasswordSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthBasicAuthUsernameSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientCertSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthClientCertClientKeySecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientIdSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2ClientSecretSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams#value
   */
  readonly value?: string;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2EndpointParams | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'value': obj.value,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */

/**
 * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret
 */
export interface WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret {
  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret#key
   */
  readonly key: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret#name
   */
  readonly name?: string;

  /**
   * @schema WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret#optional
   */
  readonly optional?: boolean;

}

/**
 * Converts an object of type 'WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret' to JSON representation.
 */
/* eslint-disable max-len, quote-props */
export function toJson_WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret(obj: WorkflowEventBindingSpecSubmitArgumentsArtifactsHttpAuthOauth2TokenUrlSecret | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, quote-props */
