name: build-melt-dbt
on:
  push:
    branches: [main]
    paths: ["melt-dbt/**"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v14
        with:
          name: givonwash
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - id: build-image
        name: Build Image
        run: |
          nix build .#melt-dbt-docker-image
          echo "buildHash=$(readlink result | sed -E 's:/nix/store/(\w+)-.*:\1:')" >> $GITHUB_OUTPUT
      - name: Load Image
        run: docker load < result
      - uses: docker/login-action@v3
        with:
          username: givonwash
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Push Image
        env:
          BUILD_HASH: ${{ steps.build-image.outputs.buildHash }}
          IMAGE_REPOSITORY: givonwash/melt-dbt
        run: |
          docker tag melt-dbt:${BUILD_HASH} ${IMAGE_REPOSITORY}:${BUILD_HASH}
          docker push ${IMAGE_REPOSITORY}:${BUILD_HASH}
